version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dawheen_backend-green
    environment:
      - LANG=ko_KR.UTF-8
    ports:
      - "8081:8080"
    networks:
      - spring-network
    volumes:
      - file-upload:/dawheen/uploads/
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22182:2181"
    networks:
      - spring-network
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "29093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - spring-network
  redis:
    image: redis:6.0.20
    ports:
      - "6381:6379"
    networks:
      - spring-network
networks:
  spring-network:

volumes:
  mysql-data:
  file-upload: